### PR TITLE
[RFC] Scoped completion chains

### PR DESCRIPTION
**Pull request by vigoux**
This is basically completion chains that are used based on the curent
syntax group (customizable).

Seraching order is as follows :
    * current ft current syntax group
    * default current syntax group
    * current ft default
    * default default

Syntax group keys in scoped chain completions are regexes that will match
case insensitively the current syntax group.

EDIT: Wrong search order

### CODE REVIEW

**Comment by haorenW1025** [comment]
Thanks for the work!!! I have some question though.
1. What does `completion_syntax_at_point` at point stands for? Maybe it's not implemented yet?
2. When getting syntax by synIDattr(), links of highlight group would be a problem. The following gif is a simple example using the dracula theme.
Kapture 2020-04-01 at 0 57 02
I've looked it up and maybe here can be a method to try.

**Comment by vigoux** [comment]
> 1. What does `completion_syntax_at_point` at point stands for? Maybe it's not implemented yet?

It will be a way to customize how you get the syntax element at point (looking for better integration with treesitter). By default its only the highlight group, but it could be the treesitter node or whatever. 

> 2. When getting syntax by synIDattr(), links of highlight group would be a problem. The following gif is a simple example using the dracula theme.

Oh yeah, I'm looking into this right now.

**Comment by vigoux** [comment]
Should fix the problem of strange `synIDattr`in this comment.

**Comment by vigoux** [comment]
Some comments though :
1. The way chains are used drastically changed in the last few commits, and maintaining a backward compatibility seems to be a pain
2. We need a way to be sure that the chains dictionnary have a `['default']['default']` key, and maybe, allowing user only to add items to the chains, not directly through a variable, but through some API might allow some more flexibility on our side, while being more secure and stable on users' side.

**Comment by haorenW1025** [comment]
> The way chains are used drastically changed in the last few commits, and maintaining a backward compatibility seems to be a pain

Maintaining backward compatibility not only preserve stable for user but also allow different way of setting chain completion list. For example users may not need scope completion but just need different filetype completion list.

> We need a way to be sure that the chains dictionnary have a ['default']['default'] key, and maybe, allowing user only to add items to the chains, not directly through a variable, but through some API might allow some more flexibility on our side, while being more secure and stable on users' side

I think using variable is still more intuitive though. In addition, we can use `metatable` to prevent getting nil value, for example
```.lua
local default_completion_list = {
  {ins_complete= false, complete_items= {'lsp', 'snippet'}},
  {ins_complete= true, mode= '<c-n>'}
}

chain_complete_list = setmetatable(chain_complete_list,{
   __index = function(_, key)
        if key ~= 'default' then
            return nil
        else
            return default_completion_list
        end
    end
})

```
By using this we can ensure to return a pre-defined default list if key "default" is not exists.

**Comment by vigoux** [comment]
> I think using variable is still more intuitive though. In addition, we can use `metatable` to prevent getting nil value, for example
> 
> ```lua
> local default_completion_list = {
>   {ins_complete= false, complete_items= {'lsp', 'snippet'}},
>   {ins_complete= true, mode= '<c-n>'}
> }
> 
> chain_complete_list = setmetatable(chain_complete_list,{
>    __index = function(_, key)
>         if key ~= 'default' then
>             return nil
>         else
>             return default_completion_list
>         end
>     end
> })
> ```
> 
> By using this we can ensure to return a pre-defined default list if key "default" is not exists.

Oh, I didn't know that we can do that, I'm going to look into this.

Another this we might be looking for is removing this `inc_complete` key in the dict, and only checking if a given key is present in the completion item.

**Comment by haorenW1025** [comment]
> Another this we might be looking for is removing this `inc_complete` key in the dict, and only checking if a given key is present in the completion item.

Yeah I have to admit that the `inc_complete` key is kind of annoying, but I can't come up with a good way to remove it because I want to allow defining multiple non-insert complete items in one source. Insertcomplete method cannot be concat in such a way so that why `inc-complete` key exists. Do you have some suggestion on how can we deal with this problem?

**Comment by vigoux** [comment]
I'm going to try and find a way to do it but in my opinion, checking is a the key doing things like this might work :
```lua
complete_items = {
    { mode = '<c-n>'},
    { sources = {'lsp', 'snippet'}
}
```

And then checking like this : 
```lua
for _, complete_item in ipairs(complete_items) do
  if vim.fn.has_key(complete_item, 'mode') > 0 then
  -- ins_complete things...
  elseif vim.fn.has_key(complete_item, 'sources') > 0 then
  -- custom sources things
  else
  -- Error, malformed completion item
  end
end
```

**Comment by haorenW1025** [comment]
Yeah I think that's pretty neat. Maybe we should change it directly in this PR.

**Comment by vigoux** [comment]
Should be added by last commit, the neat thing is that it is backward compatible.

**Comment by haorenW1025** [comment]
>  I don't know if I'm clear but basically, the whole part of scoped completion chains would move to the `__index` function, which would simplify how the plugin works quite a lot.

But will moving that to `__index` function make user harder to set up with vimscript(with defining a variable)?

**Comment by vigoux** [comment]
I haven't tried, but the only thing `__index` will do is change the lua side and handle things for us, on vimscript side, it will basically not change.

**Comment by vigoux** [comment]
Okay, did a bit of rework around all of this, basically, the plugin transforms the chain list inot a tree before using it, this first step greatly simplifies the way we handle it afterwards, and allow greater flexibility on users' side.

**Comment by haorenW1025** [comment]
Test it out but this will produce some bugs. 
1. When `chain_complete_list[filetype]` is `nil` the function `getScopedChain` cannot catch it correctly. Maybe add a line `if ft_subtree == nil then return end` in the beginning of `getScopedChain`
2. line 109 in `source.lua` would index a nil value if `chain_complete_list[filetype]` is nil, maybe need a wrapper function and prevent getting nil value.
These bugs can be reproduced using a filetype that's not specified in `chain_complete_list`.

Tested out the scope completion and it seems to work, but a minor thing, having user to set it up with regex is quite tedious, since most of the time the regex should be the same. Can we let user specify the scope and insert the regex pattern by ourselves? Something like `'.*'..syntax..'.*'`

**Comment by vigoux** [comment]
>    These bugs can be reproduced using a filetype that's not specified in `chain_complete_list`.

Yep, thought about that but forgot it in the implementation actually

> Tested out the scope completion and it seems to work, but a minor thing, having user to set it up with regex is quite tedious, since most of the time the regex should be the same. Can we let user specify the scope and insert the regex pattern by ourselves? Something like `'.*'..syntax..'.*'`

Yeah that's much much nicer !

**Comment by vigoux** [comment]
Should be okay in this version.

After some thinking, I did some tests, but it did not raised me any errors.

**Comment by haorenW1025** [comment]
Test it out, works great so far! Thank you so much!

**Comment by vigoux** [comment]
I'll test plugin integration with treesitter notably.

BTW, [the plugin is out](https://github.com/vigoux/completion-treesitter), nothing have moved for now, but it will in the near future !

**Pull request merged**
