### PR TITLE
feat: multiple matching strategy

### PR DESCRIPTION
**Pull request by haorenW1025**
Implement suggested feature in #66.

- [x] implement multiple matching strategy
- [x] configurable users option
- [x] case insensitive matching
- [x] allow per server setup of matching and sorting
- [x] wrap the multiple matching into an API to provide easier custom source integration
- [x] Refactor
- [x] Documentation

### CODE REVIEW

**Comment by haorenW1025** [comment]
@clason You can try setting up per-server option by 
```lua
  require'completion'.on_attach({
      sorter = 'alphabet',
      matcher = {'exact', 'fuzzy'}
    })
```
Let me know what you think:)

**Comment by clason** [comment]
I'm using 
```lua
require'completion'.on_attach({sorter = 'none', matcher = {'exact', 'substring', 'fuzzy'}})
```
and getting
```
Error executing vim.schedule lua callback: ...n/.cache/nvim/plugins/completion-nvim/lua/source/lsp.lua:69: attempt to call a nil value
```

**Comment by haorenW1025** [comment]
Oh I use `substr` actually...I can change it to `substring`.

**Comment by clason** [comment]
No, `substr` is fine, I just needed to know ;)

**Pull request merged**
